# Generated by Django 5.1.4 on 2024-12-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_attendee_id_alter_email_id_alter_events_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='events.events'),
        ),
        migrations.AddField(
            model_name='email',
            name='option',
            field=models.CharField(choices=[('registration', 'Registration Mail'), ('24hr_reminder', '24 Hours Reminder'), ('1hr_reminder', '1 Hour Reminder')], default='registration', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(default='You have registered for', max_length=200),
        ),
    ]
