# Generated by Django 5.1.4 on 2024-12-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_email_event_email_option_alter_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='registration_data',
            field=models.JSONField(default=dict),
        ),
    ]
